### ISSUE TITLE
git prompt support --git-dir?

### ISSUE THREAD

**Issue by rieje** [joshdick/dotfiles#1]
I've been using your [git prompt](https://joshdick.net/2012/12/30/my_git_prompt_for_zsh.html) and am absolutely loving it--it's simple and clean. I recently switched to a [bare git repo](https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/) approach to managing dotfiles where it references my dotfile repo `~/.dotfiles.git` and uses `--work-tree=$HOME`. It also uses branches to manage dotfiles across my machines--machine-specific config go to their respective $HOST branch while config share by all my machines reside in the master branch. 

It is important to distinguish between the branches, which is why I'm wondering if you can help me add support for my specific scenario where the git prompt should show when I'm at $HOME (since this is where dotfiles reside) and the states (e.g. information like what branch you're in) should correspond to  the bare git repo `~/.dotfiles.git`.

At the moment, for managing dotfiles using a bare git repo, the git prompt will not show up unless I'm inside the bare git repo (as expected), but if using the dotfile management described in the post I've linked, it'd make more sense if it shows up in `~`.

Any help is much appreciated--I really want to continue using this git prompt.

**Comment by joshdick** [comment]
This is somewhat of a hack, but here's the shortest way I can think to accomplish this (untested.)

At the top of the `git_info()` function, add the following:

```bash
if [[ "$PWD" = "$HOME" ]]; then
  export GIT_DIR="$HOME/.dotfiles.git"
fi
```

This should cause all subsequent `git` commands in that function to use the bare repo as Git's `.git` folder when your shell's working directory is your home directory (Git's work tree).

You may want to do `unset GIT_DIR` at the very end of that function just to be safe, though the `export` should have no effect since the file it executes in shouldn't be sourced by the shell (just executed normally.)

I'm not sure what, if any, other unintended consequences this might have.
